version: '1'
rules: # Array of rules
  - base: master # Required. Target branch
    upstream: wei:master # Required. Must be in the same fork network.
    mergeMethod: hardreset # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: custom-react-scripts
    upstream: master # Required. Can be a branch in the same forked repo.
    assignees: # Optional
      - StanFaas
    reviewers: # Optional
      - StanFaas
label: ':arrow_heading_down: pull' # Optional
